### ISSUE TITLE
JS heap out of memory fatal error

### ISSUE THREAD

**Issue by innomaxx** [DarkMannn/you-shall-not-pass#1]
In code:
![image](https://user-images.githubusercontent.com/40697586/57881668-8feacc80-782a-11e9-9ae2-e560f224fdcf.png)

Throws:
![image](https://user-images.githubusercontent.com/40697586/57881629-79447580-782a-11e9-9113-460fd38bf2a2.png)

**Comment by DarkMannn** [comment]
Looking at your code, first thing that comes to my attention is wrong usage of `readable` event. That is it should not be mixed with `.pipe()` method, because of high probability of producing unexpected results.
Because that event  gets fired every time that new piece of data can be read from a readable stream (which is response object in this case), and as a consequence `.pipe` method gets called multiple times, causing heap to go out of memory.

I would suggest either using `readable` event with `readable.read()` API or just `readable.pipe()` as per official Node.js documentation.

**Comment by innomaxx** [comment]
Thanks, I'll try it.
